spring:
  application:
    name: rabbitMQ_consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
    virtual-host: /spring_cloud
#    若使用confirm-callback或return-callback，必须要配置publisherConfirms或publisherReturns为true
    publisher-confirms: true
    publisher-returns: true

server:
  port: 8002
